nextjs (#27)

diff --git a/Dockerfile.caprover b/Dockerfile.caprover
--- a/Dockerfile.caprover
+++ b/Dockerfile.caprover
@@ -1,26 +1,56 @@
-FROM node:18.15.0-alpine as builder
-ARG REACT_APP_GOOGLE_ANALYTICS_ID
-ARG REACT_APP_POSTHOG_ID
-ENV REACT_APP_GOOGLE_ANALYTICS_ID=$REACT_APP_GOOGLE_ANALYTICS_ID
-ENV REACT_APP_POSTHOG_ID=$REACT_APP_POSTHOG_ID
+FROM node:18.15.0-alpine AS base
 
+### Dependencies
+ARG GOOGLE_TAG_ID
+ARG POSTHOG_ID
+ENV NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID=$GOOGLE_TAG_ID
+ENV NEXT_PUBLIC_POSTHOG_ID=$POSTHOG_ID
+
+# Install dependencies only when needed
+FROM base AS deps
+# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
+RUN apk add --no-cache libc6-compat
 # Set the working directory to /app inside the container
 WORKDIR /app
-# Copy app files
+# Install dependencies based on the preferred package manager
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
+RUN \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
+
+### Builder
+# Rebuild the source code only when needed
+FROM base AS builder
+# Change environment variables
+WORKDIR /app
+COPY --from=deps /app/node_modules ./node_modules
 COPY . .
-# Install dependencies (npm ci makes sure the exact versions in the lockfile gets installed)
-RUN npm ci 
-# Build the app
+
 RUN npm run build
 
-# Bundle static assets with nginx
-FROM nginx:1.21.0-alpine as production
+### Runner
+# Production image, copy all the files and run next
+FROM base AS runner
+WORKDIR /app
+# Set Environment
 ENV NODE_ENV production
-# Copy built assets from `builder` image
-COPY --from=builder /app/build /usr/share/nginx/html
-# Add your nginx.conf
-COPY nginx.conf /etc/nginx/conf.d/default.conf
-# Expose port
-EXPOSE 80
-# Start nginx
-CMD ["nginx", "-g", "daemon off;"]
+
+RUN addgroup --system --gid 1001 nodejs
+RUN adduser --system --uid 1001 nextjs
+COPY --from=builder /app/public ./public
+COPY --from=builder /app/node_modules ./node_modules
+COPY --from=builder /app/package.json ./package.json
+COPY --from=builder /app/.next ./.next
+# Automatically leverage output traces to reduce image size
+# https://nextjs.org/docs/advanced-features/output-file-tracing
+# COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
+# COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
+
+USER nextjs
+EXPOSE 3000
+ENV PORT 3000
+
+CMD ["npm", "start"]
